// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNPy1VP00iFPJPFwkfr7VbKxhCvqj70Js',
    appId: '1:266849350424:web:c6152269221a371b48a46d',
    messagingSenderId: '266849350424',
    projectId: 'gesitshop-dd1c4',
    authDomain: 'gesitshop-dd1c4.firebaseapp.com',
    storageBucket: 'gesitshop-dd1c4.appspot.com',
    measurementId: 'G-97PH0X21HN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqUOmWfij5sygDR-ifUkUlGO3p8E4GRrE',
    appId: '1:266849350424:android:f121daef9b3dcf5048a46d',
    messagingSenderId: '266849350424',
    projectId: 'gesitshop-dd1c4',
    storageBucket: 'gesitshop-dd1c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiUnoDTmceoyDNuPcOaRU_EEfJCV7x-Io',
    appId: '1:266849350424:ios:c5441534c49b144448a46d',
    messagingSenderId: '266849350424',
    projectId: 'gesitshop-dd1c4',
    storageBucket: 'gesitshop-dd1c4.appspot.com',
    iosBundleId: 'com.example.flutterGesitshop',
  );
}
